apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: wp
spec:
  storageClassName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi