apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: myservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # hostPath:
  #   path: "/mnt/data/marianadb"
---
